### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by edgexie** [1milligram/this-vs-that#226]
Help, My env : node v14.20.0, npm v6.14.17 
![image](https://user-images.githubusercontent.com/18474752/183221707-0f2b12a0-c7b7-40a6-b3f2-d804ce31c712.png)

**Comment by circletop** [comment]
有解决吗

**Comment by edgexie** [comment]
> 有解决吗

没有，你也遇到了？

**Comment by circletop** [comment]
> 

解决了，按着它提示 安装了 依赖

**Comment by edgexie** [comment]
@circletop 是说按照提示 `yarn add --dev @types/react` 了么？ 我装了也不行的。

**Comment by joshuadelange** [comment]
This is what fixed it for me:

```
npm install next@latest
npm install --save-dev @types/node
```
